### ISSUE TITLE
Terraform can't load plugin schemas.

### ISSUE THREAD

**Issue by harysonii** [SyedK1987/terraform-provider-sendgrid#2]
<img width="359" alt="Screenshot 2024-04-30 at 08 17 52" src="https://github.com/SyedK1987/terraform-provider-sendgrid/assets/26610671/3c7a27af-3a18-4680-9409-beee1d7a73a3">

Hi @SyedK1987 ,

I get this error every time I run terraform plan/apply.

**Comment by code-ninja99** [comment]
> <img alt="Screenshot 2024-04-30 at 08 17 52" width="359" src="https://private-user-images.githubusercontent.com/26610671/326708114-3c7a27af-3a18-4680-9409-beee1d7a73a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1MTM2ODMsIm5iZiI6MTcxNDUxMzM4MywicGF0aCI6Ii8yNjYxMDY3MS8zMjY3MDgxMTQtM2M3YTI3YWYtM2ExOC00NjgwLTk0MDktYmVlZTFkN2E3M2EzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDIxNDMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcyNTc0OWM4NmY5MDQ2ZDk2OWJlZDIwZTc4YzVhOTVmMDNiN2FmMDQwOWJmMjA5ZDg1N2M5ZjMyOWQxMDkyZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.p3dmPhu1blImth1vJJC4yqKhua1Me0wYiX_feBB9zDo">
> 
> Hi @SyedK1987 ,
> 
> I get this error every time I run terraform plan/apply.

I will check on this and come back to you.

**Comment by harysonii** [comment]
Thank you @SyedK1987 


resource "sendgrid_single_sender" "ssender" {
  nickname      = local.smtp_nickname
  from_email    = var.smtp_admin_user
  from_name     = local.smtp_sender_name
  reply_to      = local.smtp_reply_to
  reply_to_name = local.smtp_reply_to_name
  address       = var.smtp_addr
  address2      = var.smtp_addr_2
  city          = var.smtp_city
  state         = var.smtp_state
  zip           = var.smtp_zip_code
  country       = "NGA"
}

resource "sendgrid_domain_authentication" "this" {
  domain      = var.domain
  is_default  = true
  environment = "prod"
}


resource "sendgrid_linkbrand" "link" {
  domain    = "example.com"
  default   = true      # if you want to make this domain as default domain then change this value to true.
}

resource "digitalocean_record" "domain_auth_0" {
  domain   = var.domain
  type     = upper(sendgrid_domain_authentication.this.dns[0].type)
  name     = trimsuffix(sendgrid_domain_authentication.this.dns[0].host, ".${var.domain}")
  value    = sendgrid_domain_authentication.this.dns[0].data
  priority = upper("${sendgrid_domain_authentication.this.dns[0].type}") == "MX" ? 10 : null
  ttl      = local.ttl[upper(sendgrid_domain_authentication.this.dns[0].type)]
}

resource "digitalocean_record" "domain_auth_1" {
  domain   = var.domain
  type     = upper(sendgrid_domain_authentication.this.dns[1].type)
  name     = trimsuffix(sendgrid_domain_authentication.this.dns[1].host, ".${var.domain}")
  value    = sendgrid_domain_authentication.this.dns[1].data
  priority = upper("${sendgrid_domain_authentication.this.dns[1].type}") == "MX" ? 10 : null
  ttl      = local.ttl[upper(sendgrid_domain_authentication.this.dns[1].type)]
}

resource "digitalocean_record" "domain_auth_2" {
  domain   = var.domain
  type     = upper(sendgrid_domain_authentication.this.dns[2].type)
  name     = trimsuffix(sendgrid_domain_authentication.this.dns[2].host, ".${var.domain}")
  value    = sendgrid_domain_authentication.this.dns[2].data
  priority = upper("${sendgrid_domain_authentication.this.dns[2].type}") == "MX" ? 10 : null
  ttl      = local.ttl[upper(sendgrid_domain_authentication.this.dns[2].type)]
}

resource "digitalocean_record" "link_brand_0" {
  domain = var.domain
  type   = upper("${sendgrid_linkbrand.this.dns[0].type}")
  name   = trimsuffix(sendgrid_linkbrand.this.dns[0].host, ".${var.domain}")
  value  = upper("${sendgrid_linkbrand.this.dns[0].type}") == "CNAME" ? "${sendgrid_linkbrand.this.dns[0].data}." : sendgrid_linkbrand.this.dns[0].data
  ttl    = local.ttl[upper(sendgrid_linkbrand.this.dns[0].type)]
}

resource "digitalocean_record" "link_brand_1" {
  domain = var.domain
  type   = upper("${sendgrid_linkbrand.this.dns[1].type}")
  name   = trimsuffix(sendgrid_linkbrand.this.dns[1].host, ".${var.domain}")
  value  = upper("${sendgrid_linkbrand.this.dns[1].type}") == "CNAME" ? "${sendgrid_linkbrand.this.dns[1].data}." : sendgrid_linkbrand.this.dns[1].data
  ttl    = local.ttl[upper(sendgrid_linkbrand.this.dns[1].type)]
}

resource "sendgrid_api_key" "this" {
  name = "orion-sendgrid"
  scopes = [
    "mail.send"
  ]
}


This is my sendgrid.tf file

provider "sendgrid" {
    apikey: ""
}

**Comment by code-ninja99** [comment]
> Thank you @SyedK1987
> 
> resource "sendgrid_single_sender" "ssender" { nickname = local.smtp_nickname from_email = var.smtp_admin_user from_name = local.smtp_sender_name reply_to = local.smtp_reply_to reply_to_name = local.smtp_reply_to_name address = var.smtp_addr address2 = var.smtp_addr_2 city = var.smtp_city state = var.smtp_state zip = var.smtp_zip_code country = "NGA" }
> 
> resource "sendgrid_domain_authentication" "this" { domain = var.domain is_default = true environment = "prod" }
> 
> resource "sendgrid_linkbrand" "link" { domain = "example.com" default = true # if you want to make this domain as default domain then change this value to true. }
> 
> resource "digitalocean_record" "domain_auth_0" { domain = var.domain type = upper(sendgrid_domain_authentication.this.dns[0].type) name = trimsuffix(sendgrid_domain_authentication.this.dns[0].host, ".${var.domain}") value = sendgrid_domain_authentication.this.dns[0].data priority = upper("${sendgrid_domain_authentication.this.dns[0].type}") == "MX" ? 10 : null ttl = local.ttl[upper(sendgrid_domain_authentication.this.dns[0].type)] }
> 
> resource "digitalocean_record" "domain_auth_1" { domain = var.domain type = upper(sendgrid_domain_authentication.this.dns[1].type) name = trimsuffix(sendgrid_domain_authentication.this.dns[1].host, ".${var.domain}") value = sendgrid_domain_authentication.this.dns[1].data priority = upper("${sendgrid_domain_authentication.this.dns[1].type}") == "MX" ? 10 : null ttl = local.ttl[upper(sendgrid_domain_authentication.this.dns[1].type)] }
> 
> resource "digitalocean_record" "domain_auth_2" { domain = var.domain type = upper(sendgrid_domain_authentication.this.dns[2].type) name = trimsuffix(sendgrid_domain_authentication.this.dns[2].host, ".${var.domain}") value = sendgrid_domain_authentication.this.dns[2].data priority = upper("${sendgrid_domain_authentication.this.dns[2].type}") == "MX" ? 10 : null ttl = local.ttl[upper(sendgrid_domain_authentication.this.dns[2].type)] }
> 
> resource "digitalocean_record" "link_brand_0" { domain = var.domain type = upper("${sendgrid_linkbrand.this.dns[0].type}") name = trimsuffix(sendgrid_linkbrand.this.dns[0].host, ".${var.domain}") value = upper("${sendgrid_linkbrand.this.dns[0].type}") == "CNAME" ? "${sendgrid_linkbrand.this.dns[0].data}." : sendgrid_linkbrand.this.dns[0].data ttl = local.ttl[upper(sendgrid_linkbrand.this.dns[0].type)] }
> 
> resource "digitalocean_record" "link_brand_1" { domain = var.domain type = upper("${sendgrid_linkbrand.this.dns[1].type}") name = trimsuffix(sendgrid_linkbrand.this.dns[1].host, ".${var.domain}") value = upper("${sendgrid_linkbrand.this.dns[1].type}") == "CNAME" ? "${sendgrid_linkbrand.this.dns[1].data}." : sendgrid_linkbrand.this.dns[1].data ttl = local.ttl[upper(sendgrid_linkbrand.this.dns[1].type)] }
> 
> resource "sendgrid_api_key" "this" { name = "orion-sendgrid" scopes = [ "mail.send" ] }
> 
> This is my sendgrid.tf file
> 
> provider "sendgrid" { apikey: "" }

Issue fixed on version 0.0.03. Please let me know if you have further challenges.

There is known warning not an issue with statefile of api_key. you can ignore that i will fix in future release

**Comment by harysonii** [comment]
Thank you, I will check it out.

**Comment by code-ninja99** [comment]
Issue Fixed in latest version.
